### PR TITLE
Custom Error responses

### PR DESCRIPTION
**Pull request by Krylphi**
Refactored previous MR with a suggested more general approach via 
```
        WriteError func(w ResponseWriter, error string, code int)
```
Also added tests

### CODE REVIEW

**Comment by pascaldekloe** [comment]
Nice work. 👍

**Comment by pascaldekloe** [comment]
Do you need a release with this feature inn b.t.w.? Or can you work on a snapshot?

**Comment by Krylphi** [comment]
> Do you need a release with this feature inn b.t.w.? Or can you work on a snapshot?

I would prefer some kind of stable release, if possible. I've done my patch on a branch from v1.6.0 and currently referring to my repository. It's not a blocker for now. Thank you.

**Comment by pascaldekloe** [comment]
OK, then I'll make a release tonight.

This patch broke the tests <https://circleci.com/gh/pascaldekloe/jwt> b.t.w.. I'll undo the changes and apply an example (test) instead, so people can see how to use this feature. As a rule, always try to add tests rather than changing them.

```go
// custom error response
WriteError: func(w http.ResponseWriter, error string, statusCode int) {
        w.Header().Set("Content-Type", "application/json;charset=UTF-8")
        w.WriteHeader(statusCode)
        fmt.Fprintf(w, `{"msg": %q}`, error)
},
```

**Comment by pascaldekloe** [comment]
Renamed WriteError to just Error b.t.w. That is a bit more compliant with the naming from net/http.

**Comment by Krylphi** [comment]
>This patch broke the tests https://circleci.com/gh/pascaldekloe/jwt b.t.w.. 

it seems like they broke, because of  "no HTTP Authorization" error message from 1.6 was changed to "no HTTP Authorization header" in master. I've been testing on 1.6 version, which was the latest stable release. So they would probably break anyway, whether I add tests or edit. 

>As a rule, always try to add tests rather than changing them.

I'll keep that in mind about tests. 

> OK, then I'll make a release tonight.

Thank you.

**Pull request merged**
